'use client'
import './globals.css'
import { ThemeProvider, CssBaseline } from '@mui/material'
import { darkTheme } from './theme/themes'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
/*
body:before {
background: none;
}
*/
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <body className="bg-none">
          <main className="w-full h-screen bg-gray-950 p-6">{children}</main>
        </body>
      </ThemeProvider>
    </html>
  )
}
