'use client'
import './globals.css'
import { ThemeProvider, CssBaseline } from '@mui/material'
import { darkTheme } from './theme/themes'
import ThemeRegistry from './theme/ThemeRegistry'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
/*
body:before {
background: none;
}
*/
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <ThemeRegistry>
        <body className="bg-none" id="__next">
          <main className="w-full h-screen bg-cover p-6">{children}</main>
        </body>
      </ThemeRegistry>
    </html>
  )
}
